site_name: ftSwarm.py - Help and Reference
copyright: "&copy; Christian Bergschneider & Stefan Fuss"
site_url: https://ftswarm-py.bloeckchengrafik.de

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - 'quickstart.md'
  - Reference: '/reference'
  - 'Issue Tracker': 'https://github.com/Bloeckchengrafik/ftswarm.py'