site_name: ftSwarm.py - Help and Reference
copyright: "&copy; Christian Bergschneider & Stefan Fuss"
site_url: https://bloeckchengrafik.de/ftswarm.py

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - 'quickstart.md'
  - Reference: '/ftswarm.py/reference/swarm.html'
  - 'Issue Tracker': 'https://github.com/Bloeckchengrafik/ftswarm.py'